# Generated by Django 4.2.5 on 2024-02-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muskeer', '0004_meep'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
