# Generated by Django 4.2.5 on 2024-03-01 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muskeer', '0005_profile_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='meepLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
